use log;

/// Represents a standardized security alert generated by a detection heuristic.
/// Centralizing this structure ensures all telemetry output maintains a consistent format
/// for downstream SIEM ingestion or console monitoring.
pub struct SyscallAlert {
    pub detector_name: &'static str,
    pub process_id: u32,
    pub primary_action: String,
    pub context: Vec<(&'static str, String)>,
}

impl SyscallAlert {
    /// Dispatches the configured alert to the standard logging facility.
    /// Uses visual boundaries to ensure high visibility in terminal streams.
    pub fn fire(&self) {
        log::warn!("\n==================================================");
        log::warn!("[!!!] {} TRIGGERED [!!!]", self.detector_name.to_uppercase());
        log::warn!("==================================================");
        log::warn!("PID    : {}", self.process_id);
        log::warn!("ACTION : {}", self.primary_action);
        
        for (key, value) in &self.context {
            log::warn!(" -> {}: {}", key, value);
        }
        log::warn!("==================================================\n");
    }
}